/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package yajco.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BOOLEAN = 1;
  /** RegularExpression Id. */
  int INTEGER = 2;
  /** RegularExpression Id. */
  int REAL = 3;
  /** RegularExpression Id. */
  int STRING = 4;
  /** RegularExpression Id. */
  int NAME = 5;
  /** RegularExpression Id. */
  int BOOLEAN_VALUE = 6;
  /** RegularExpression Id. */
  int REAL_VALUE = 7;
  /** RegularExpression Id. */
  int STRING_VALUE = 8;
  /** RegularExpression Id. */
  int INT_VALUE = 9;
  /** RegularExpression Id. */
  int CONCEPT = 10;
  /** RegularExpression Id. */
  int _58 = 11;
  /** RegularExpression Id. */
  int _123 = 12;
  /** RegularExpression Id. */
  int OPERATOR = 13;
  /** RegularExpression Id. */
  int _40 = 14;
  /** RegularExpression Id. */
  int PRIORITY = 15;
  /** RegularExpression Id. */
  int _61 = 16;
  /** RegularExpression Id. */
  int _41 = 17;
  /** RegularExpression Id. */
  int ASSOCIATIVITY = 18;
  /** RegularExpression Id. */
  int LEFT = 19;
  /** RegularExpression Id. */
  int RIGHT = 20;
  /** RegularExpression Id. */
  int NONE = 21;
  /** RegularExpression Id. */
  int AUTO = 22;
  /** RegularExpression Id. */
  int PARENTHESES = 23;
  /** RegularExpression Id. */
  int _44 = 24;
  /** RegularExpression Id. */
  int _125 = 25;
  /** RegularExpression Id. */
  int AS = 26;
  /** RegularExpression Id. */
  int ARRAY = 27;
  /** RegularExpression Id. */
  int OF = 28;
  /** RegularExpression Id. */
  int IDENTIFIER = 29;
  /** RegularExpression Id. */
  int CS = 30;
  /** RegularExpression Id. */
  int _124 = 31;
  /** RegularExpression Id. */
  int SEPARATOR = 32;
  /** RegularExpression Id. */
  int REFERENCES = 33;
  /** RegularExpression Id. */
  int PROPERTY = 34;
  /** RegularExpression Id. */
  int RANGE = 35;
  /** RegularExpression Id. */
  int _46_46 = 36;
  /** RegularExpression Id. */
  int _42 = 37;
  /** RegularExpression Id. */
  int INDENT = 38;
  /** RegularExpression Id. */
  int NEWLINE = 39;
  /** RegularExpression Id. */
  int LANGUAGE = 40;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"BOOLEAN\"",
    "\"INTEGER\"",
    "\"REAL\"",
    "\"STRING\"",
    "\"NAME\"",
    "\"BOOLEAN_VALUE\"",
    "\"REAL_VALUE\"",
    "\"STRING_VALUE\"",
    "\"INT_VALUE\"",
    "\"CONCEPT\"",
    "\"_58\"",
    "\"_123\"",
    "\"OPERATOR\"",
    "\"_40\"",
    "\"PRIORITY\"",
    "\"_61\"",
    "\"_41\"",
    "\"ASSOCIATIVITY\"",
    "\"LEFT\"",
    "\"RIGHT\"",
    "\"NONE\"",
    "\"AUTO\"",
    "\"PARENTHESES\"",
    "\"_44\"",
    "\"_125\"",
    "\"AS\"",
    "\"ARRAY\"",
    "\"OF\"",
    "\"IDENTIFIER\"",
    "\"CS\"",
    "\"_124\"",
    "\"SEPARATOR\"",
    "\"REFERENCES\"",
    "\"PROPERTY\"",
    "\"RANGE\"",
    "\"_46_46\"",
    "\"_42\"",
    "\"INDENT\"",
    "\"NEWLINE\"",
    "\"LANGUAGE\"",
  };

}
