/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package yajco.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BOOLEAN = 1;
  /** RegularExpression Id. */
  int INTEGER = 2;
  /** RegularExpression Id. */
  int REAL = 3;
  /** RegularExpression Id. */
  int STRING = 4;
  /** RegularExpression Id. */
  int NAME = 5;
  /** RegularExpression Id. */
  int BOOLEAN_VALUE = 6;
  /** RegularExpression Id. */
  int REAL_VALUE = 7;
  /** RegularExpression Id. */
  int STRING_VALUE = 8;
  /** RegularExpression Id. */
  int INT_VALUE = 9;
  /** RegularExpression Id. */
  int TOKENS = 10;
  /** RegularExpression Id. */
  int _61 = 11;
  /** RegularExpression Id. */
  int SKIPS = 12;
  /** RegularExpression Id. */
  int CONCEPT = 13;
  /** RegularExpression Id. */
  int _58 = 14;
  /** RegularExpression Id. */
  int _123 = 15;
  /** RegularExpression Id. */
  int PARENTHESES = 16;
  /** RegularExpression Id. */
  int _40 = 17;
  /** RegularExpression Id. */
  int _44 = 18;
  /** RegularExpression Id. */
  int _41 = 19;
  /** RegularExpression Id. */
  int OPERATOR = 20;
  /** RegularExpression Id. */
  int PRIORITY = 21;
  /** RegularExpression Id. */
  int ASSOCIATIVITY = 22;
  /** RegularExpression Id. */
  int LEFT = 23;
  /** RegularExpression Id. */
  int RIGHT = 24;
  /** RegularExpression Id. */
  int NONE = 25;
  /** RegularExpression Id. */
  int AUTO = 26;
  /** RegularExpression Id. */
  int ENUM = 27;
  /** RegularExpression Id. */
  int _125 = 28;
  /** RegularExpression Id. */
  int AS = 29;
  /** RegularExpression Id. */
  int ARRAY = 30;
  /** RegularExpression Id. */
  int OF = 31;
  /** RegularExpression Id. */
  int LIST = 32;
  /** RegularExpression Id. */
  int SET = 33;
  /** RegularExpression Id. */
  int IDENTIFIER = 34;
  /** RegularExpression Id. */
  int CS = 35;
  /** RegularExpression Id. */
  int _124 = 36;
  /** RegularExpression Id. */
  int SEPARATOR = 37;
  /** RegularExpression Id. */
  int RANGE = 38;
  /** RegularExpression Id. */
  int _46_46 = 39;
  /** RegularExpression Id. */
  int _42 = 40;
  /** RegularExpression Id. */
  int NEWLINE = 41;
  /** RegularExpression Id. */
  int REFERENCES = 42;
  /** RegularExpression Id. */
  int PROPERTY = 43;
  /** RegularExpression Id. */
  int INDENT = 44;
  /** RegularExpression Id. */
  int FACTORY = 45;
  /** RegularExpression Id. */
  int METHOD = 46;
  /** RegularExpression Id. */
  int LANGUAGE = 47;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"BOOLEAN\"",
    "\"INTEGER\"",
    "\"REAL\"",
    "\"STRING\"",
    "\"NAME\"",
    "\"BOOLEAN_VALUE\"",
    "\"REAL_VALUE\"",
    "\"STRING_VALUE\"",
    "\"INT_VALUE\"",
    "\"TOKENS\"",
    "\"_61\"",
    "\"SKIPS\"",
    "\"CONCEPT\"",
    "\"_58\"",
    "\"_123\"",
    "\"PARENTHESES\"",
    "\"_40\"",
    "\"_44\"",
    "\"_41\"",
    "\"OPERATOR\"",
    "\"PRIORITY\"",
    "\"ASSOCIATIVITY\"",
    "\"LEFT\"",
    "\"RIGHT\"",
    "\"NONE\"",
    "\"AUTO\"",
    "\"ENUM\"",
    "\"_125\"",
    "\"AS\"",
    "\"ARRAY\"",
    "\"OF\"",
    "\"LIST\"",
    "\"SET\"",
    "\"IDENTIFIER\"",
    "\"CS\"",
    "\"_124\"",
    "\"SEPARATOR\"",
    "\"RANGE\"",
    "\"_46_46\"",
    "\"_42\"",
    "\"NEWLINE\"",
    "\"REFERENCES\"",
    "\"PROPERTY\"",
    "\"INDENT\"",
    "\"FACTORY\"",
    "\"METHOD\"",
    "\"LANGUAGE\"",
  };

}
